/******************************************************************************
* This file was generated by ZenStack CLI.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { type RouterFactory, type ProcBuilder, type BaseConfig, db } from ".";
import * as _Schema from '@zenstackhq/runtime/zod/input';
const $Schema: typeof _Schema = (_Schema as any).default ?? _Schema;
import { checkRead, checkMutate } from '../helper';

export default function createRouter<Config extends BaseConfig>(router: RouterFactory<Config>, procedure: ProcBuilder<Config>) {
    return router({

        createMany: procedure.input($Schema.AchievementInputSchema.createMany.optional()).mutation(async ({ ctx, input }) => checkMutate(db(ctx).achievement.createMany(input as any))),

        create: procedure.input($Schema.AchievementInputSchema.create).mutation(async ({ ctx, input }) => checkMutate(db(ctx).achievement.create(input as any))),

        deleteMany: procedure.input($Schema.AchievementInputSchema.deleteMany.optional()).mutation(async ({ ctx, input }) => checkMutate(db(ctx).achievement.deleteMany(input as any))),

        delete: procedure.input($Schema.AchievementInputSchema.delete).mutation(async ({ ctx, input }) => checkMutate(db(ctx).achievement.delete(input as any))),

        findFirst: procedure.input($Schema.AchievementInputSchema.findFirst.optional()).query(({ ctx, input }) => checkRead(db(ctx).achievement.findFirst(input as any))),

        findMany: procedure.input($Schema.AchievementInputSchema.findMany.optional()).query(({ ctx, input }) => checkRead(db(ctx).achievement.findMany(input as any))),

        findUnique: procedure.input($Schema.AchievementInputSchema.findUnique).query(({ ctx, input }) => checkRead(db(ctx).achievement.findUnique(input as any))),

        updateMany: procedure.input($Schema.AchievementInputSchema.updateMany).mutation(async ({ ctx, input }) => checkMutate(db(ctx).achievement.updateMany(input as any))),

        update: procedure.input($Schema.AchievementInputSchema.update).mutation(async ({ ctx, input }) => checkMutate(db(ctx).achievement.update(input as any))),

        count: procedure.input($Schema.AchievementInputSchema.count.optional()).query(({ ctx, input }) => checkRead(db(ctx).achievement.count(input as any))),

    }
    );
}
