/******************************************************************************
* This file was generated by ZenStack CLI.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { type RouterFactory, type ProcBuilder, type BaseConfig, db } from ".";
import * as _Schema from '@zenstackhq/runtime/zod/input';
const $Schema: typeof _Schema = (_Schema as any).default ?? _Schema;
import { checkRead, checkMutate } from '../helper';

export default function createRouter<Config extends BaseConfig>(router: RouterFactory<Config>, procedure: ProcBuilder<Config>) {
    return router({

        createMany: procedure.input($Schema.CommunityInputSchema.createMany.optional()).mutation(async ({ ctx, input }) => checkMutate(db(ctx).community.createMany(input as any))),

        create: procedure.input($Schema.CommunityInputSchema.create).mutation(async ({ ctx, input }) => checkMutate(db(ctx).community.create(input as any))),

        deleteMany: procedure.input($Schema.CommunityInputSchema.deleteMany.optional()).mutation(async ({ ctx, input }) => checkMutate(db(ctx).community.deleteMany(input as any))),

        delete: procedure.input($Schema.CommunityInputSchema.delete).mutation(async ({ ctx, input }) => checkMutate(db(ctx).community.delete(input as any))),

        findFirst: procedure.input($Schema.CommunityInputSchema.findFirst.optional()).query(({ ctx, input }) => checkRead(db(ctx).community.findFirst(input as any))),

        findMany: procedure.input($Schema.CommunityInputSchema.findMany.optional()).query(({ ctx, input }) => checkRead(db(ctx).community.findMany(input as any))),

        findUnique: procedure.input($Schema.CommunityInputSchema.findUnique).query(({ ctx, input }) => checkRead(db(ctx).community.findUnique(input as any))),

        updateMany: procedure.input($Schema.CommunityInputSchema.updateMany).mutation(async ({ ctx, input }) => checkMutate(db(ctx).community.updateMany(input as any))),

        update: procedure.input($Schema.CommunityInputSchema.update).mutation(async ({ ctx, input }) => checkMutate(db(ctx).community.update(input as any))),

        count: procedure.input($Schema.CommunityInputSchema.count.optional()).query(({ ctx, input }) => checkRead(db(ctx).community.count(input as any))),

    }
    );
}
