/******************************************************************************
* This file was generated by ZenStack CLI.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { type RouterFactory, type ProcBuilder, type BaseConfig, db } from ".";
import * as _Schema from '@zenstackhq/runtime/zod/input';
const $Schema: typeof _Schema = (_Schema as any).default ?? _Schema;
import { checkRead, checkMutate } from '../helper';

export default function createRouter<Config extends BaseConfig>(router: RouterFactory<Config>, procedure: ProcBuilder<Config>) {
    return router({

        createMany: procedure.input($Schema.DiscussionInputSchema.createMany.optional()).mutation(async ({ ctx, input }) => checkMutate(db(ctx).discussion.createMany(input as any))),

        create: procedure.input($Schema.DiscussionInputSchema.create).mutation(async ({ ctx, input }) => checkMutate(db(ctx).discussion.create(input as any))),

        deleteMany: procedure.input($Schema.DiscussionInputSchema.deleteMany.optional()).mutation(async ({ ctx, input }) => checkMutate(db(ctx).discussion.deleteMany(input as any))),

        delete: procedure.input($Schema.DiscussionInputSchema.delete).mutation(async ({ ctx, input }) => checkMutate(db(ctx).discussion.delete(input as any))),

        findFirst: procedure.input($Schema.DiscussionInputSchema.findFirst.optional()).query(({ ctx, input }) => checkRead(db(ctx).discussion.findFirst(input as any))),

        findMany: procedure.input($Schema.DiscussionInputSchema.findMany.optional()).query(({ ctx, input }) => checkRead(db(ctx).discussion.findMany(input as any))),

        findUnique: procedure.input($Schema.DiscussionInputSchema.findUnique).query(({ ctx, input }) => checkRead(db(ctx).discussion.findUnique(input as any))),

        updateMany: procedure.input($Schema.DiscussionInputSchema.updateMany).mutation(async ({ ctx, input }) => checkMutate(db(ctx).discussion.updateMany(input as any))),

        update: procedure.input($Schema.DiscussionInputSchema.update).mutation(async ({ ctx, input }) => checkMutate(db(ctx).discussion.update(input as any))),

        count: procedure.input($Schema.DiscussionInputSchema.count.optional()).query(({ ctx, input }) => checkRead(db(ctx).discussion.count(input as any))),

    }
    );
}
