/******************************************************************************
* This file was generated by ZenStack CLI.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { type RouterFactory, type ProcBuilder, type BaseConfig, db } from ".";
import * as _Schema from '@zenstackhq/runtime/zod/input';
const $Schema: typeof _Schema = (_Schema as any).default ?? _Schema;
import { checkRead, checkMutate } from '../helper';

export default function createRouter<Config extends BaseConfig>(router: RouterFactory<Config>, procedure: ProcBuilder<Config>) {
    return router({

        createMany: procedure.input($Schema.EventInputSchema.createMany.optional()).mutation(async ({ ctx, input }) => checkMutate(db(ctx).event.createMany(input as any))),

        create: procedure.input($Schema.EventInputSchema.create).mutation(async ({ ctx, input }) => checkMutate(db(ctx).event.create(input as any))),

        deleteMany: procedure.input($Schema.EventInputSchema.deleteMany.optional()).mutation(async ({ ctx, input }) => checkMutate(db(ctx).event.deleteMany(input as any))),

        delete: procedure.input($Schema.EventInputSchema.delete).mutation(async ({ ctx, input }) => checkMutate(db(ctx).event.delete(input as any))),

        findFirst: procedure.input($Schema.EventInputSchema.findFirst.optional()).query(({ ctx, input }) => checkRead(db(ctx).event.findFirst(input as any))),

        findMany: procedure.input($Schema.EventInputSchema.findMany.optional()).query(({ ctx, input }) => checkRead(db(ctx).event.findMany(input as any))),

        findUnique: procedure.input($Schema.EventInputSchema.findUnique).query(({ ctx, input }) => checkRead(db(ctx).event.findUnique(input as any))),

        updateMany: procedure.input($Schema.EventInputSchema.updateMany).mutation(async ({ ctx, input }) => checkMutate(db(ctx).event.updateMany(input as any))),

        update: procedure.input($Schema.EventInputSchema.update).mutation(async ({ ctx, input }) => checkMutate(db(ctx).event.update(input as any))),

        count: procedure.input($Schema.EventInputSchema.count.optional()).query(({ ctx, input }) => checkRead(db(ctx).event.count(input as any))),

    }
    );
}
