/******************************************************************************
* This file was generated by ZenStack CLI.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { type RouterFactory, type ProcBuilder, type BaseConfig, db } from ".";
import * as _Schema from '@zenstackhq/runtime/zod/input';
const $Schema: typeof _Schema = (_Schema as any).default ?? _Schema;
import { checkRead, checkMutate } from '../helper';

export default function createRouter<Config extends BaseConfig>(router: RouterFactory<Config>, procedure: ProcBuilder<Config>) {
    return router({

        createMany: procedure.input($Schema.EventRegistrationInputSchema.createMany.optional()).mutation(async ({ ctx, input }) => checkMutate(db(ctx).eventRegistration.createMany(input as any))),

        create: procedure.input($Schema.EventRegistrationInputSchema.create).mutation(async ({ ctx, input }) => checkMutate(db(ctx).eventRegistration.create(input as any))),

        deleteMany: procedure.input($Schema.EventRegistrationInputSchema.deleteMany.optional()).mutation(async ({ ctx, input }) => checkMutate(db(ctx).eventRegistration.deleteMany(input as any))),

        delete: procedure.input($Schema.EventRegistrationInputSchema.delete).mutation(async ({ ctx, input }) => checkMutate(db(ctx).eventRegistration.delete(input as any))),

        findFirst: procedure.input($Schema.EventRegistrationInputSchema.findFirst.optional()).query(({ ctx, input }) => checkRead(db(ctx).eventRegistration.findFirst(input as any))),

        findMany: procedure.input($Schema.EventRegistrationInputSchema.findMany.optional()).query(({ ctx, input }) => checkRead(db(ctx).eventRegistration.findMany(input as any))),

        findUnique: procedure.input($Schema.EventRegistrationInputSchema.findUnique).query(({ ctx, input }) => checkRead(db(ctx).eventRegistration.findUnique(input as any))),

        updateMany: procedure.input($Schema.EventRegistrationInputSchema.updateMany).mutation(async ({ ctx, input }) => checkMutate(db(ctx).eventRegistration.updateMany(input as any))),

        update: procedure.input($Schema.EventRegistrationInputSchema.update).mutation(async ({ ctx, input }) => checkMutate(db(ctx).eventRegistration.update(input as any))),

        count: procedure.input($Schema.EventRegistrationInputSchema.count.optional()).query(({ ctx, input }) => checkRead(db(ctx).eventRegistration.count(input as any))),

    }
    );
}
