/******************************************************************************
* This file was generated by ZenStack CLI.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { type RouterFactory, type ProcBuilder, type BaseConfig, db } from ".";
import * as _Schema from '@zenstackhq/runtime/zod/input';
const $Schema: typeof _Schema = (_Schema as any).default ?? _Schema;
import { checkRead, checkMutate } from '../helper';

export default function createRouter<Config extends BaseConfig>(router: RouterFactory<Config>, procedure: ProcBuilder<Config>) {
    return router({

        createMany: procedure.input($Schema.PwaSubscriptionInputSchema.createMany.optional()).mutation(async ({ ctx, input }) => checkMutate(db(ctx).pwaSubscription.createMany(input as any))),

        create: procedure.input($Schema.PwaSubscriptionInputSchema.create).mutation(async ({ ctx, input }) => checkMutate(db(ctx).pwaSubscription.create(input as any))),

        deleteMany: procedure.input($Schema.PwaSubscriptionInputSchema.deleteMany.optional()).mutation(async ({ ctx, input }) => checkMutate(db(ctx).pwaSubscription.deleteMany(input as any))),

        delete: procedure.input($Schema.PwaSubscriptionInputSchema.delete).mutation(async ({ ctx, input }) => checkMutate(db(ctx).pwaSubscription.delete(input as any))),

        findFirst: procedure.input($Schema.PwaSubscriptionInputSchema.findFirst.optional()).query(({ ctx, input }) => checkRead(db(ctx).pwaSubscription.findFirst(input as any))),

        findMany: procedure.input($Schema.PwaSubscriptionInputSchema.findMany.optional()).query(({ ctx, input }) => checkRead(db(ctx).pwaSubscription.findMany(input as any))),

        findUnique: procedure.input($Schema.PwaSubscriptionInputSchema.findUnique).query(({ ctx, input }) => checkRead(db(ctx).pwaSubscription.findUnique(input as any))),

        updateMany: procedure.input($Schema.PwaSubscriptionInputSchema.updateMany).mutation(async ({ ctx, input }) => checkMutate(db(ctx).pwaSubscription.updateMany(input as any))),

        update: procedure.input($Schema.PwaSubscriptionInputSchema.update).mutation(async ({ ctx, input }) => checkMutate(db(ctx).pwaSubscription.update(input as any))),

        count: procedure.input($Schema.PwaSubscriptionInputSchema.count.optional()).query(({ ctx, input }) => checkRead(db(ctx).pwaSubscription.count(input as any))),

    }
    );
}
