/******************************************************************************
* This file was generated by ZenStack CLI.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { Prisma } from '@zenstackhq/runtime/models';
import type { TRPCClientErrorLike, TRPCRequestOptions } from '@trpc/client';
import type { UseTRPCMutationOptions, UseTRPCMutationResult, UseTRPCQueryOptions, UseTRPCQueryResult, UseTRPCInfiniteQueryOptions, UseTRPCInfiniteQueryResult } from '@trpc/react-query/shared';
import type { AnyRouter } from '@trpc/server';

export interface ClientType<AppRouter extends AnyRouter, Context = AppRouter['_def']['_config']['$types']['ctx']> {
    createMany: {

        useMutation: <T extends Prisma.EventCreateManyArgs>(opts?: UseTRPCMutationOptions<
            Prisma.EventCreateManyArgs,
            TRPCClientErrorLike<AppRouter>,
            Prisma.BatchPayload,
            Context
        >) =>
            Omit<UseTRPCMutationResult<Prisma.BatchPayload, TRPCClientErrorLike<AppRouter>, Prisma.SelectSubset<T, Prisma.EventCreateManyArgs>, Context>, 'mutateAsync'> & {
                mutateAsync:
                <T extends Prisma.EventCreateManyArgs>(variables?: T, opts?: UseTRPCMutationOptions<T, TRPCClientErrorLike<AppRouter>, Prisma.BatchPayload, Context>) => Promise<Prisma.BatchPayload>
            };

    };
    create: {

        useMutation: <T extends Prisma.EventCreateArgs>(opts?: UseTRPCMutationOptions<
            Prisma.EventCreateArgs,
            TRPCClientErrorLike<AppRouter>,
            Prisma.EventGetPayload<T>,
            Context
        >) =>
            Omit<UseTRPCMutationResult<Prisma.EventGetPayload<T>, TRPCClientErrorLike<AppRouter>, Prisma.SelectSubset<T, Prisma.EventCreateArgs>, Context>, 'mutateAsync'> & {
                mutateAsync:
                <T extends Prisma.EventCreateArgs>(variables: T, opts?: UseTRPCMutationOptions<T, TRPCClientErrorLike<AppRouter>, Prisma.EventGetPayload<T>, Context>) => Promise<Prisma.EventGetPayload<T>>
            };

    };
    deleteMany: {

        useMutation: <T extends Prisma.EventDeleteManyArgs>(opts?: UseTRPCMutationOptions<
            Prisma.EventDeleteManyArgs,
            TRPCClientErrorLike<AppRouter>,
            Prisma.BatchPayload,
            Context
        >) =>
            Omit<UseTRPCMutationResult<Prisma.BatchPayload, TRPCClientErrorLike<AppRouter>, Prisma.SelectSubset<T, Prisma.EventDeleteManyArgs>, Context>, 'mutateAsync'> & {
                mutateAsync:
                <T extends Prisma.EventDeleteManyArgs>(variables?: T, opts?: UseTRPCMutationOptions<T, TRPCClientErrorLike<AppRouter>, Prisma.BatchPayload, Context>) => Promise<Prisma.BatchPayload>
            };

    };
    delete: {

        useMutation: <T extends Prisma.EventDeleteArgs>(opts?: UseTRPCMutationOptions<
            Prisma.EventDeleteArgs,
            TRPCClientErrorLike<AppRouter>,
            Prisma.EventGetPayload<T>,
            Context
        >) =>
            Omit<UseTRPCMutationResult<Prisma.EventGetPayload<T>, TRPCClientErrorLike<AppRouter>, Prisma.SelectSubset<T, Prisma.EventDeleteArgs>, Context>, 'mutateAsync'> & {
                mutateAsync:
                <T extends Prisma.EventDeleteArgs>(variables: T, opts?: UseTRPCMutationOptions<T, TRPCClientErrorLike<AppRouter>, Prisma.EventGetPayload<T>, Context>) => Promise<Prisma.EventGetPayload<T>>
            };

    };
    findFirst: {

        useQuery: <T extends Prisma.EventFindFirstArgs, TData = Prisma.EventGetPayload<T> | null>(
            input?: Prisma.SelectSubset<T, Prisma.EventFindFirstArgs>,
            opts?: UseTRPCQueryOptions<string, T, Prisma.EventGetPayload<T> | null, TData, Error>
        ) => UseTRPCQueryResult<
            TData,
            TRPCClientErrorLike<AppRouter>
        >;
        useInfiniteQuery: <T extends Prisma.EventFindFirstArgs>(
            input?: Omit<Prisma.SelectSubset<T, Prisma.EventFindFirstArgs>, 'cursor'>,
            opts?: UseTRPCInfiniteQueryOptions<string, T, Prisma.EventGetPayload<T> | null, Error>
        ) => UseTRPCInfiniteQueryResult<
            Prisma.EventGetPayload<T> | null,
            TRPCClientErrorLike<AppRouter>
        >;

    };
    findMany: {

        useQuery: <T extends Prisma.EventFindManyArgs, TData = Array<Prisma.EventGetPayload<T>>>(
            input?: Prisma.SelectSubset<T, Prisma.EventFindManyArgs>,
            opts?: UseTRPCQueryOptions<string, T, Array<Prisma.EventGetPayload<T>>, TData, Error>
        ) => UseTRPCQueryResult<
            TData,
            TRPCClientErrorLike<AppRouter>
        >;
        useInfiniteQuery: <T extends Prisma.EventFindManyArgs>(
            input?: Omit<Prisma.SelectSubset<T, Prisma.EventFindManyArgs>, 'cursor'>,
            opts?: UseTRPCInfiniteQueryOptions<string, T, Array<Prisma.EventGetPayload<T>>, Error>
        ) => UseTRPCInfiniteQueryResult<
            Array<Prisma.EventGetPayload<T>>,
            TRPCClientErrorLike<AppRouter>
        >;

    };
    findUnique: {

        useQuery: <T extends Prisma.EventFindUniqueArgs, TData = Prisma.EventGetPayload<T> | null>(
            input: Prisma.SelectSubset<T, Prisma.EventFindUniqueArgs>,
            opts?: UseTRPCQueryOptions<string, T, Prisma.EventGetPayload<T> | null, TData, Error>
        ) => UseTRPCQueryResult<
            TData,
            TRPCClientErrorLike<AppRouter>
        >;
        useInfiniteQuery: <T extends Prisma.EventFindUniqueArgs>(
            input: Omit<Prisma.SelectSubset<T, Prisma.EventFindUniqueArgs>, 'cursor'>,
            opts?: UseTRPCInfiniteQueryOptions<string, T, Prisma.EventGetPayload<T> | null, Error>
        ) => UseTRPCInfiniteQueryResult<
            Prisma.EventGetPayload<T> | null,
            TRPCClientErrorLike<AppRouter>
        >;

    };
    updateMany: {

        useMutation: <T extends Prisma.EventUpdateManyArgs>(opts?: UseTRPCMutationOptions<
            Prisma.EventUpdateManyArgs,
            TRPCClientErrorLike<AppRouter>,
            Prisma.BatchPayload,
            Context
        >) =>
            Omit<UseTRPCMutationResult<Prisma.BatchPayload, TRPCClientErrorLike<AppRouter>, Prisma.SelectSubset<T, Prisma.EventUpdateManyArgs>, Context>, 'mutateAsync'> & {
                mutateAsync:
                <T extends Prisma.EventUpdateManyArgs>(variables: T, opts?: UseTRPCMutationOptions<T, TRPCClientErrorLike<AppRouter>, Prisma.BatchPayload, Context>) => Promise<Prisma.BatchPayload>
            };

    };
    update: {

        useMutation: <T extends Prisma.EventUpdateArgs>(opts?: UseTRPCMutationOptions<
            Prisma.EventUpdateArgs,
            TRPCClientErrorLike<AppRouter>,
            Prisma.EventGetPayload<T>,
            Context
        >) =>
            Omit<UseTRPCMutationResult<Prisma.EventGetPayload<T>, TRPCClientErrorLike<AppRouter>, Prisma.SelectSubset<T, Prisma.EventUpdateArgs>, Context>, 'mutateAsync'> & {
                mutateAsync:
                <T extends Prisma.EventUpdateArgs>(variables: T, opts?: UseTRPCMutationOptions<T, TRPCClientErrorLike<AppRouter>, Prisma.EventGetPayload<T>, Context>) => Promise<Prisma.EventGetPayload<T>>
            };

    };
    count: {

        useQuery: <T extends Prisma.EventCountArgs, TData = 'select' extends keyof T
            ? T['select'] extends true
            ? number
            : Prisma.GetScalarType<T['select'], Prisma.EventCountAggregateOutputType>
            : number>(
                input?: Prisma.Subset<T, Prisma.EventCountArgs>,
                opts?: UseTRPCQueryOptions<string, T, 'select' extends keyof T
                    ? T['select'] extends true
                    ? number
                    : Prisma.GetScalarType<T['select'], Prisma.EventCountAggregateOutputType>
                    : number, TData, Error>
            ) => UseTRPCQueryResult<
                TData,
                TRPCClientErrorLike<AppRouter>
            >;
        useInfiniteQuery: <T extends Prisma.EventCountArgs>(
            input?: Omit<Prisma.Subset<T, Prisma.EventCountArgs>, 'cursor'>,
            opts?: UseTRPCInfiniteQueryOptions<string, T, 'select' extends keyof T
                ? T['select'] extends true
                ? number
                : Prisma.GetScalarType<T['select'], Prisma.EventCountAggregateOutputType>
                : number, Error>
        ) => UseTRPCInfiniteQueryResult<
            'select' extends keyof T
            ? T['select'] extends true
            ? number
            : Prisma.GetScalarType<T['select'], Prisma.EventCountAggregateOutputType>
            : number,
            TRPCClientErrorLike<AppRouter>
        >;

    };
}
