/******************************************************************************
* This file was generated by ZenStack CLI.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { Prisma } from '@zenstackhq/runtime/models';
import type { TRPCClientErrorLike, TRPCRequestOptions } from '@trpc/client';
import type { UseTRPCMutationOptions, UseTRPCMutationResult, UseTRPCQueryOptions, UseTRPCQueryResult, UseTRPCInfiniteQueryOptions, UseTRPCInfiniteQueryResult } from '@trpc/react-query/shared';
import type { AnyRouter } from '@trpc/server';

export interface ClientType<AppRouter extends AnyRouter, Context = AppRouter['_def']['_config']['$types']['ctx']> {
    createMany: {

        useMutation: <T extends Prisma.EventRegistrationCreateManyArgs>(opts?: UseTRPCMutationOptions<
            Prisma.EventRegistrationCreateManyArgs,
            TRPCClientErrorLike<AppRouter>,
            Prisma.BatchPayload,
            Context
        >) =>
            Omit<UseTRPCMutationResult<Prisma.BatchPayload, TRPCClientErrorLike<AppRouter>, Prisma.SelectSubset<T, Prisma.EventRegistrationCreateManyArgs>, Context>, 'mutateAsync'> & {
                mutateAsync:
                <T extends Prisma.EventRegistrationCreateManyArgs>(variables?: T, opts?: UseTRPCMutationOptions<T, TRPCClientErrorLike<AppRouter>, Prisma.BatchPayload, Context>) => Promise<Prisma.BatchPayload>
            };

    };
    create: {

        useMutation: <T extends Prisma.EventRegistrationCreateArgs>(opts?: UseTRPCMutationOptions<
            Prisma.EventRegistrationCreateArgs,
            TRPCClientErrorLike<AppRouter>,
            Prisma.EventRegistrationGetPayload<T>,
            Context
        >) =>
            Omit<UseTRPCMutationResult<Prisma.EventRegistrationGetPayload<T>, TRPCClientErrorLike<AppRouter>, Prisma.SelectSubset<T, Prisma.EventRegistrationCreateArgs>, Context>, 'mutateAsync'> & {
                mutateAsync:
                <T extends Prisma.EventRegistrationCreateArgs>(variables: T, opts?: UseTRPCMutationOptions<T, TRPCClientErrorLike<AppRouter>, Prisma.EventRegistrationGetPayload<T>, Context>) => Promise<Prisma.EventRegistrationGetPayload<T>>
            };

    };
    deleteMany: {

        useMutation: <T extends Prisma.EventRegistrationDeleteManyArgs>(opts?: UseTRPCMutationOptions<
            Prisma.EventRegistrationDeleteManyArgs,
            TRPCClientErrorLike<AppRouter>,
            Prisma.BatchPayload,
            Context
        >) =>
            Omit<UseTRPCMutationResult<Prisma.BatchPayload, TRPCClientErrorLike<AppRouter>, Prisma.SelectSubset<T, Prisma.EventRegistrationDeleteManyArgs>, Context>, 'mutateAsync'> & {
                mutateAsync:
                <T extends Prisma.EventRegistrationDeleteManyArgs>(variables?: T, opts?: UseTRPCMutationOptions<T, TRPCClientErrorLike<AppRouter>, Prisma.BatchPayload, Context>) => Promise<Prisma.BatchPayload>
            };

    };
    delete: {

        useMutation: <T extends Prisma.EventRegistrationDeleteArgs>(opts?: UseTRPCMutationOptions<
            Prisma.EventRegistrationDeleteArgs,
            TRPCClientErrorLike<AppRouter>,
            Prisma.EventRegistrationGetPayload<T>,
            Context
        >) =>
            Omit<UseTRPCMutationResult<Prisma.EventRegistrationGetPayload<T>, TRPCClientErrorLike<AppRouter>, Prisma.SelectSubset<T, Prisma.EventRegistrationDeleteArgs>, Context>, 'mutateAsync'> & {
                mutateAsync:
                <T extends Prisma.EventRegistrationDeleteArgs>(variables: T, opts?: UseTRPCMutationOptions<T, TRPCClientErrorLike<AppRouter>, Prisma.EventRegistrationGetPayload<T>, Context>) => Promise<Prisma.EventRegistrationGetPayload<T>>
            };

    };
    findFirst: {

        useQuery: <T extends Prisma.EventRegistrationFindFirstArgs, TData = Prisma.EventRegistrationGetPayload<T> | null>(
            input?: Prisma.SelectSubset<T, Prisma.EventRegistrationFindFirstArgs>,
            opts?: UseTRPCQueryOptions<string, T, Prisma.EventRegistrationGetPayload<T> | null, TData, Error>
        ) => UseTRPCQueryResult<
            TData,
            TRPCClientErrorLike<AppRouter>
        >;
        useInfiniteQuery: <T extends Prisma.EventRegistrationFindFirstArgs>(
            input?: Omit<Prisma.SelectSubset<T, Prisma.EventRegistrationFindFirstArgs>, 'cursor'>,
            opts?: UseTRPCInfiniteQueryOptions<string, T, Prisma.EventRegistrationGetPayload<T> | null, Error>
        ) => UseTRPCInfiniteQueryResult<
            Prisma.EventRegistrationGetPayload<T> | null,
            TRPCClientErrorLike<AppRouter>
        >;

    };
    findMany: {

        useQuery: <T extends Prisma.EventRegistrationFindManyArgs, TData = Array<Prisma.EventRegistrationGetPayload<T>>>(
            input?: Prisma.SelectSubset<T, Prisma.EventRegistrationFindManyArgs>,
            opts?: UseTRPCQueryOptions<string, T, Array<Prisma.EventRegistrationGetPayload<T>>, TData, Error>
        ) => UseTRPCQueryResult<
            TData,
            TRPCClientErrorLike<AppRouter>
        >;
        useInfiniteQuery: <T extends Prisma.EventRegistrationFindManyArgs>(
            input?: Omit<Prisma.SelectSubset<T, Prisma.EventRegistrationFindManyArgs>, 'cursor'>,
            opts?: UseTRPCInfiniteQueryOptions<string, T, Array<Prisma.EventRegistrationGetPayload<T>>, Error>
        ) => UseTRPCInfiniteQueryResult<
            Array<Prisma.EventRegistrationGetPayload<T>>,
            TRPCClientErrorLike<AppRouter>
        >;

    };
    findUnique: {

        useQuery: <T extends Prisma.EventRegistrationFindUniqueArgs, TData = Prisma.EventRegistrationGetPayload<T> | null>(
            input: Prisma.SelectSubset<T, Prisma.EventRegistrationFindUniqueArgs>,
            opts?: UseTRPCQueryOptions<string, T, Prisma.EventRegistrationGetPayload<T> | null, TData, Error>
        ) => UseTRPCQueryResult<
            TData,
            TRPCClientErrorLike<AppRouter>
        >;
        useInfiniteQuery: <T extends Prisma.EventRegistrationFindUniqueArgs>(
            input: Omit<Prisma.SelectSubset<T, Prisma.EventRegistrationFindUniqueArgs>, 'cursor'>,
            opts?: UseTRPCInfiniteQueryOptions<string, T, Prisma.EventRegistrationGetPayload<T> | null, Error>
        ) => UseTRPCInfiniteQueryResult<
            Prisma.EventRegistrationGetPayload<T> | null,
            TRPCClientErrorLike<AppRouter>
        >;

    };
    updateMany: {

        useMutation: <T extends Prisma.EventRegistrationUpdateManyArgs>(opts?: UseTRPCMutationOptions<
            Prisma.EventRegistrationUpdateManyArgs,
            TRPCClientErrorLike<AppRouter>,
            Prisma.BatchPayload,
            Context
        >) =>
            Omit<UseTRPCMutationResult<Prisma.BatchPayload, TRPCClientErrorLike<AppRouter>, Prisma.SelectSubset<T, Prisma.EventRegistrationUpdateManyArgs>, Context>, 'mutateAsync'> & {
                mutateAsync:
                <T extends Prisma.EventRegistrationUpdateManyArgs>(variables: T, opts?: UseTRPCMutationOptions<T, TRPCClientErrorLike<AppRouter>, Prisma.BatchPayload, Context>) => Promise<Prisma.BatchPayload>
            };

    };
    update: {

        useMutation: <T extends Prisma.EventRegistrationUpdateArgs>(opts?: UseTRPCMutationOptions<
            Prisma.EventRegistrationUpdateArgs,
            TRPCClientErrorLike<AppRouter>,
            Prisma.EventRegistrationGetPayload<T>,
            Context
        >) =>
            Omit<UseTRPCMutationResult<Prisma.EventRegistrationGetPayload<T>, TRPCClientErrorLike<AppRouter>, Prisma.SelectSubset<T, Prisma.EventRegistrationUpdateArgs>, Context>, 'mutateAsync'> & {
                mutateAsync:
                <T extends Prisma.EventRegistrationUpdateArgs>(variables: T, opts?: UseTRPCMutationOptions<T, TRPCClientErrorLike<AppRouter>, Prisma.EventRegistrationGetPayload<T>, Context>) => Promise<Prisma.EventRegistrationGetPayload<T>>
            };

    };
    count: {

        useQuery: <T extends Prisma.EventRegistrationCountArgs, TData = 'select' extends keyof T
            ? T['select'] extends true
            ? number
            : Prisma.GetScalarType<T['select'], Prisma.EventRegistrationCountAggregateOutputType>
            : number>(
                input?: Prisma.Subset<T, Prisma.EventRegistrationCountArgs>,
                opts?: UseTRPCQueryOptions<string, T, 'select' extends keyof T
                    ? T['select'] extends true
                    ? number
                    : Prisma.GetScalarType<T['select'], Prisma.EventRegistrationCountAggregateOutputType>
                    : number, TData, Error>
            ) => UseTRPCQueryResult<
                TData,
                TRPCClientErrorLike<AppRouter>
            >;
        useInfiniteQuery: <T extends Prisma.EventRegistrationCountArgs>(
            input?: Omit<Prisma.Subset<T, Prisma.EventRegistrationCountArgs>, 'cursor'>,
            opts?: UseTRPCInfiniteQueryOptions<string, T, 'select' extends keyof T
                ? T['select'] extends true
                ? number
                : Prisma.GetScalarType<T['select'], Prisma.EventRegistrationCountAggregateOutputType>
                : number, Error>
        ) => UseTRPCInfiniteQueryResult<
            'select' extends keyof T
            ? T['select'] extends true
            ? number
            : Prisma.GetScalarType<T['select'], Prisma.EventRegistrationCountAggregateOutputType>
            : number,
            TRPCClientErrorLike<AppRouter>
        >;

    };
}
