/******************************************************************************
* This file was generated by ZenStack CLI.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { Prisma } from '@zenstackhq/runtime/models';
import type { TRPCClientErrorLike, TRPCRequestOptions } from '@trpc/client';
import type { UseTRPCMutationOptions, UseTRPCMutationResult, UseTRPCQueryOptions, UseTRPCQueryResult, UseTRPCInfiniteQueryOptions, UseTRPCInfiniteQueryResult } from '@trpc/react-query/shared';
import type { AnyRouter } from '@trpc/server';

export interface ClientType<AppRouter extends AnyRouter, Context = AppRouter['_def']['_config']['$types']['ctx']> {
    createMany: {

        useMutation: <T extends Prisma.PwaSubscriptionCreateManyArgs>(opts?: UseTRPCMutationOptions<
            Prisma.PwaSubscriptionCreateManyArgs,
            TRPCClientErrorLike<AppRouter>,
            Prisma.BatchPayload,
            Context
        >) =>
            Omit<UseTRPCMutationResult<Prisma.BatchPayload, TRPCClientErrorLike<AppRouter>, Prisma.SelectSubset<T, Prisma.PwaSubscriptionCreateManyArgs>, Context>, 'mutateAsync'> & {
                mutateAsync:
                <T extends Prisma.PwaSubscriptionCreateManyArgs>(variables?: T, opts?: UseTRPCMutationOptions<T, TRPCClientErrorLike<AppRouter>, Prisma.BatchPayload, Context>) => Promise<Prisma.BatchPayload>
            };

    };
    create: {

        useMutation: <T extends Prisma.PwaSubscriptionCreateArgs>(opts?: UseTRPCMutationOptions<
            Prisma.PwaSubscriptionCreateArgs,
            TRPCClientErrorLike<AppRouter>,
            Prisma.PwaSubscriptionGetPayload<T>,
            Context
        >) =>
            Omit<UseTRPCMutationResult<Prisma.PwaSubscriptionGetPayload<T>, TRPCClientErrorLike<AppRouter>, Prisma.SelectSubset<T, Prisma.PwaSubscriptionCreateArgs>, Context>, 'mutateAsync'> & {
                mutateAsync:
                <T extends Prisma.PwaSubscriptionCreateArgs>(variables: T, opts?: UseTRPCMutationOptions<T, TRPCClientErrorLike<AppRouter>, Prisma.PwaSubscriptionGetPayload<T>, Context>) => Promise<Prisma.PwaSubscriptionGetPayload<T>>
            };

    };
    deleteMany: {

        useMutation: <T extends Prisma.PwaSubscriptionDeleteManyArgs>(opts?: UseTRPCMutationOptions<
            Prisma.PwaSubscriptionDeleteManyArgs,
            TRPCClientErrorLike<AppRouter>,
            Prisma.BatchPayload,
            Context
        >) =>
            Omit<UseTRPCMutationResult<Prisma.BatchPayload, TRPCClientErrorLike<AppRouter>, Prisma.SelectSubset<T, Prisma.PwaSubscriptionDeleteManyArgs>, Context>, 'mutateAsync'> & {
                mutateAsync:
                <T extends Prisma.PwaSubscriptionDeleteManyArgs>(variables?: T, opts?: UseTRPCMutationOptions<T, TRPCClientErrorLike<AppRouter>, Prisma.BatchPayload, Context>) => Promise<Prisma.BatchPayload>
            };

    };
    delete: {

        useMutation: <T extends Prisma.PwaSubscriptionDeleteArgs>(opts?: UseTRPCMutationOptions<
            Prisma.PwaSubscriptionDeleteArgs,
            TRPCClientErrorLike<AppRouter>,
            Prisma.PwaSubscriptionGetPayload<T>,
            Context
        >) =>
            Omit<UseTRPCMutationResult<Prisma.PwaSubscriptionGetPayload<T>, TRPCClientErrorLike<AppRouter>, Prisma.SelectSubset<T, Prisma.PwaSubscriptionDeleteArgs>, Context>, 'mutateAsync'> & {
                mutateAsync:
                <T extends Prisma.PwaSubscriptionDeleteArgs>(variables: T, opts?: UseTRPCMutationOptions<T, TRPCClientErrorLike<AppRouter>, Prisma.PwaSubscriptionGetPayload<T>, Context>) => Promise<Prisma.PwaSubscriptionGetPayload<T>>
            };

    };
    findFirst: {

        useQuery: <T extends Prisma.PwaSubscriptionFindFirstArgs, TData = Prisma.PwaSubscriptionGetPayload<T> | null>(
            input?: Prisma.SelectSubset<T, Prisma.PwaSubscriptionFindFirstArgs>,
            opts?: UseTRPCQueryOptions<string, T, Prisma.PwaSubscriptionGetPayload<T> | null, TData, Error>
        ) => UseTRPCQueryResult<
            TData,
            TRPCClientErrorLike<AppRouter>
        >;
        useInfiniteQuery: <T extends Prisma.PwaSubscriptionFindFirstArgs>(
            input?: Omit<Prisma.SelectSubset<T, Prisma.PwaSubscriptionFindFirstArgs>, 'cursor'>,
            opts?: UseTRPCInfiniteQueryOptions<string, T, Prisma.PwaSubscriptionGetPayload<T> | null, Error>
        ) => UseTRPCInfiniteQueryResult<
            Prisma.PwaSubscriptionGetPayload<T> | null,
            TRPCClientErrorLike<AppRouter>
        >;

    };
    findMany: {

        useQuery: <T extends Prisma.PwaSubscriptionFindManyArgs, TData = Array<Prisma.PwaSubscriptionGetPayload<T>>>(
            input?: Prisma.SelectSubset<T, Prisma.PwaSubscriptionFindManyArgs>,
            opts?: UseTRPCQueryOptions<string, T, Array<Prisma.PwaSubscriptionGetPayload<T>>, TData, Error>
        ) => UseTRPCQueryResult<
            TData,
            TRPCClientErrorLike<AppRouter>
        >;
        useInfiniteQuery: <T extends Prisma.PwaSubscriptionFindManyArgs>(
            input?: Omit<Prisma.SelectSubset<T, Prisma.PwaSubscriptionFindManyArgs>, 'cursor'>,
            opts?: UseTRPCInfiniteQueryOptions<string, T, Array<Prisma.PwaSubscriptionGetPayload<T>>, Error>
        ) => UseTRPCInfiniteQueryResult<
            Array<Prisma.PwaSubscriptionGetPayload<T>>,
            TRPCClientErrorLike<AppRouter>
        >;

    };
    findUnique: {

        useQuery: <T extends Prisma.PwaSubscriptionFindUniqueArgs, TData = Prisma.PwaSubscriptionGetPayload<T> | null>(
            input: Prisma.SelectSubset<T, Prisma.PwaSubscriptionFindUniqueArgs>,
            opts?: UseTRPCQueryOptions<string, T, Prisma.PwaSubscriptionGetPayload<T> | null, TData, Error>
        ) => UseTRPCQueryResult<
            TData,
            TRPCClientErrorLike<AppRouter>
        >;
        useInfiniteQuery: <T extends Prisma.PwaSubscriptionFindUniqueArgs>(
            input: Omit<Prisma.SelectSubset<T, Prisma.PwaSubscriptionFindUniqueArgs>, 'cursor'>,
            opts?: UseTRPCInfiniteQueryOptions<string, T, Prisma.PwaSubscriptionGetPayload<T> | null, Error>
        ) => UseTRPCInfiniteQueryResult<
            Prisma.PwaSubscriptionGetPayload<T> | null,
            TRPCClientErrorLike<AppRouter>
        >;

    };
    updateMany: {

        useMutation: <T extends Prisma.PwaSubscriptionUpdateManyArgs>(opts?: UseTRPCMutationOptions<
            Prisma.PwaSubscriptionUpdateManyArgs,
            TRPCClientErrorLike<AppRouter>,
            Prisma.BatchPayload,
            Context
        >) =>
            Omit<UseTRPCMutationResult<Prisma.BatchPayload, TRPCClientErrorLike<AppRouter>, Prisma.SelectSubset<T, Prisma.PwaSubscriptionUpdateManyArgs>, Context>, 'mutateAsync'> & {
                mutateAsync:
                <T extends Prisma.PwaSubscriptionUpdateManyArgs>(variables: T, opts?: UseTRPCMutationOptions<T, TRPCClientErrorLike<AppRouter>, Prisma.BatchPayload, Context>) => Promise<Prisma.BatchPayload>
            };

    };
    update: {

        useMutation: <T extends Prisma.PwaSubscriptionUpdateArgs>(opts?: UseTRPCMutationOptions<
            Prisma.PwaSubscriptionUpdateArgs,
            TRPCClientErrorLike<AppRouter>,
            Prisma.PwaSubscriptionGetPayload<T>,
            Context
        >) =>
            Omit<UseTRPCMutationResult<Prisma.PwaSubscriptionGetPayload<T>, TRPCClientErrorLike<AppRouter>, Prisma.SelectSubset<T, Prisma.PwaSubscriptionUpdateArgs>, Context>, 'mutateAsync'> & {
                mutateAsync:
                <T extends Prisma.PwaSubscriptionUpdateArgs>(variables: T, opts?: UseTRPCMutationOptions<T, TRPCClientErrorLike<AppRouter>, Prisma.PwaSubscriptionGetPayload<T>, Context>) => Promise<Prisma.PwaSubscriptionGetPayload<T>>
            };

    };
    count: {

        useQuery: <T extends Prisma.PwaSubscriptionCountArgs, TData = 'select' extends keyof T
            ? T['select'] extends true
            ? number
            : Prisma.GetScalarType<T['select'], Prisma.PwaSubscriptionCountAggregateOutputType>
            : number>(
                input?: Prisma.Subset<T, Prisma.PwaSubscriptionCountArgs>,
                opts?: UseTRPCQueryOptions<string, T, 'select' extends keyof T
                    ? T['select'] extends true
                    ? number
                    : Prisma.GetScalarType<T['select'], Prisma.PwaSubscriptionCountAggregateOutputType>
                    : number, TData, Error>
            ) => UseTRPCQueryResult<
                TData,
                TRPCClientErrorLike<AppRouter>
            >;
        useInfiniteQuery: <T extends Prisma.PwaSubscriptionCountArgs>(
            input?: Omit<Prisma.Subset<T, Prisma.PwaSubscriptionCountArgs>, 'cursor'>,
            opts?: UseTRPCInfiniteQueryOptions<string, T, 'select' extends keyof T
                ? T['select'] extends true
                ? number
                : Prisma.GetScalarType<T['select'], Prisma.PwaSubscriptionCountAggregateOutputType>
                : number, Error>
        ) => UseTRPCInfiniteQueryResult<
            'select' extends keyof T
            ? T['select'] extends true
            ? number
            : Prisma.GetScalarType<T['select'], Prisma.PwaSubscriptionCountAggregateOutputType>
            : number,
            TRPCClientErrorLike<AppRouter>
        >;

    };
}
